In [3]:
import pandas as pd
pd.__version__

'2.2.2'

# 10 minutes to pandas

In [4]:
import numpy as np
import pandas as pd

## Object creation

In [ ]:
# Creating a Series 
s = pd.Series(np.random.randn(6), index=dates, name='values')

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [ ]:
# Creating a Dataframe by passing a Numpy array, with a datetime index using date_range() and labeled columns
dates = pd.date_range('20230101', periods=6)
dates = pd.date_range('20230101', periods=6)
dates
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
df

                   A         B         C         D
2023-01-01  1.052211  0.168218  1.461627  0.073804
2023-01-02  0.998123  0.880874  0.333953 -0.241997
2023-01-03 -0.312519 -0.751171 -1.282122  1.160103
2023-01-04  0.495067 -0.098340  0.571171 -0.925695
2023-01-05  0.798388  0.348274 -1.039914 -0.977253
2023-01-06  0.266336 -1.186428 -0.148720  1.217365

In [10]:
#Creating a DataFrame by passing a dictionary of objects where the keys are the column labels and the values are the column values.
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20230102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype='int32'),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo"
    }
)
df2

     A          B    C  D      E    F
0  1.0 2023-01-02  1.0  3   test  foo
1  1.0 2023-01-02  1.0  3  train  foo
2  1.0 2023-01-02  1.0  3   test  foo
3  1.0 2023-01-02  1.0  3  train  foo

In [12]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

# Viewing Data

In [14]:
df.head()

                   A         B         C         D
2023-01-01  1.052211  0.168218  1.461627  0.073804
2023-01-02  0.998123  0.880874  0.333953 -0.241997
2023-01-03 -0.312519 -0.751171 -1.282122  1.160103
2023-01-04  0.495067 -0.098340  0.571171 -0.925695
2023-01-05  0.798388  0.348274 -1.039914 -0.977253

In [15]:
df.tail(3)

                   A         B         C         D
2023-01-04  0.495067 -0.098340  0.571171 -0.925695
2023-01-05  0.798388  0.348274 -1.039914 -0.977253
2023-01-06  0.266336 -1.186428 -0.148720  1.217365

In [16]:
df.index

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06'],
              dtype='datetime64[ns]', freq='D')

In [17]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [18]:
df.to_numpy()

array([[ 1.05221147,  0.16821783,  1.46162737,  0.07380447],
       [ 0.99812299,  0.88087369,  0.33395269, -0.24199694],
       [-0.31251942, -0.75117122, -1.28212195,  1.16010349],
       [ 0.4950666 , -0.09833957,  0.57117097, -0.92569462],
       [ 0.79838824,  0.34827352, -1.03991375, -0.97725318],
       [ 0.2663359 , -1.18642802, -0.14871974,  1.21736518]])

In [19]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.549601 -0.106429 -0.017334  0.051055
std    0.518102  0.753539  1.031473  0.968310
min   -0.312519 -1.186428 -1.282122 -0.977253
25%    0.323519 -0.587963 -0.817115 -0.754770
50%    0.646727  0.034939  0.092616 -0.084096
75%    0.948189  0.303260  0.511866  0.888529
max    1.052211  0.880874  1.461627  1.217365

In [20]:
df.T

   2023-01-01  2023-01-02  2023-01-03  2023-01-04  2023-01-05  2023-01-06
A    1.052211    0.998123   -0.312519    0.495067    0.798388    0.266336
B    0.168218    0.880874   -0.751171   -0.098340    0.348274   -1.186428
C    1.461627    0.333953   -1.282122    0.571171   -1.039914   -0.148720
D    0.073804   -0.241997    1.160103   -0.925695   -0.977253    1.217365

In [21]:
df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2023-01-01  0.073804  1.461627  0.168218  1.052211
2023-01-02 -0.241997  0.333953  0.880874  0.998123
2023-01-03  1.160103 -1.282122 -0.751171 -0.312519
2023-01-04 -0.925695  0.571171 -0.098340  0.495067
2023-01-05 -0.977253 -1.039914  0.348274  0.798388
2023-01-06  1.217365 -0.148720 -1.186428  0.266336

In [22]:
df.sort_values(by='B')

                   A         B         C         D
2023-01-06  0.266336 -1.186428 -0.148720  1.217365
2023-01-03 -0.312519 -0.751171 -1.282122  1.160103
2023-01-04  0.495067 -0.098340  0.571171 -0.925695
2023-01-01  1.052211  0.168218  1.461627  0.073804
2023-01-05  0.798388  0.348274 -1.039914 -0.977253
2023-01-02  0.998123  0.880874  0.333953 -0.241997

In [23]:
df["A"]

2023-01-01    1.052211
2023-01-02    0.998123
2023-01-03   -0.312519
2023-01-04    0.495067
2023-01-05    0.798388
2023-01-06    0.266336
Freq: D, Name: A, dtype: float64

In [24]:
df[["A", "B"]]

                   A         B
2023-01-01  1.052211  0.168218
2023-01-02  0.998123  0.880874
2023-01-03 -0.312519 -0.751171
2023-01-04  0.495067 -0.098340
2023-01-05  0.798388  0.348274
2023-01-06  0.266336 -1.186428

In [25]:
df[0:3]

                   A         B         C         D
2023-01-01  1.052211  0.168218  1.461627  0.073804
2023-01-02  0.998123  0.880874  0.333953 -0.241997
2023-01-03 -0.312519 -0.751171 -1.282122  1.160103

In [26]:
df["20130102":"20230104"]

                   A         B         C         D
2023-01-01  1.052211  0.168218  1.461627  0.073804
2023-01-02  0.998123  0.880874  0.333953 -0.241997
2023-01-03 -0.312519 -0.751171 -1.282122  1.160103
2023-01-04  0.495067 -0.098340  0.571171 -0.925695

In [27]:
df.loc[dates[0]]

A    1.052211
B    0.168218
C    1.461627
D    0.073804
Name: 2023-01-01 00:00:00, dtype: float64

In [28]:
df.loc[:, ["A", "B"]]

                   A         B
2023-01-01  1.052211  0.168218
2023-01-02  0.998123  0.880874
2023-01-03 -0.312519 -0.751171
2023-01-04  0.495067 -0.098340
2023-01-05  0.798388  0.348274
2023-01-06  0.266336 -1.186428

In [29]:
df.loc["20230102":"20230104", ["A", "B"]]

                   A         B
2023-01-02  0.998123  0.880874
2023-01-03 -0.312519 -0.751171
2023-01-04  0.495067 -0.098340

In [30]:
df.loc[dates[0], "A"]

1.0522114684886141

# Loading Disney Data

In [35]:
df = pd.read_csv("disney_plus_shows.csv")
df.head()

,imdb_id,title,plot,type,rated,year,released_at,added_at,runtime,genre,director,writer,actors,language,country,awards,metascore,imdb_rating,imdb_votes
0,tt0147800,10 Things I Hate About You,"A pretty, popular teenager can't go out on a d...",movie,PG-13,1999,31 Mar 1999,"November 12, 2019",97 min,"Comedy, Drama, Romance",Gil Junger,"Karen McCullah, Kirsten Smith","Heath Ledger, Julia Stiles, Joseph Gordon-Levi...","English, French",USA,2 wins & 13 nominations.,70.0,7.3,"283,945"
1,tt7019028,101 Dalmatian Street,This series follows the lives of Delilah and D...,series,NaN,2018–,25 Mar 2019,"February 28, 2020",NaN,"Animation, Comedy, Family",NaN,NaN,"Josh Brener, Michaela Dietz, Bert Davis, Abiga...",English,"UK, USA, Canada",NaN,NaN,6.2,124
2,tt0115433,101 Dalmatians,An evil high-fashion designer plots to steal D...,movie,G,1996,27 Nov 1996,"November 12, 2019",103 min,"Adventure, Comedy, Crime, Family",Stephen Herek,"Dodie Smith (novel), John Hughes (screenplay)","Glenn Close, Jeff Daniels, Joely Richardson, J...","English, Spanish","USA, UK",Nominated for 1 Golden Globe. Another 3 wins &...,49.0,5.7,"97,785"
3,tt0324941,101 Dalmatians 2: Patch's London Adventure,"Being one of 101 takes its toll on Patch, who ...",movie,G,2002,21 Jan 2003,"November 12, 2019",74 min,"Animation, Adventure, Comedy, Family, Musical","Jim Kammerud, Brian Smith","Jim Kammerud (story), Dan Root (story), Garret...","Barry Bostwick, Jason Alexander, Martin Short,...",English,USA,5 wins & 10 nominations.,NaN,5.8,"7,434"
4,tt0211181,102 Dalmatians,Cruella DeVil gets out of prison and goes afte...,movie,G,2000,22 Nov 2000,"November 12, 2019",100 min,"Adventure, Comedy, Family",Kevin Lima,"Dodie Smith (novel), Kristen Buckley (story), ...","Glenn Close, Gérard Depardieu, Ioan Gruffudd, ...",English,"USA, UK",Nominated for 1 Oscar. Another 1 win & 7 nomin...,35.0,4.9,"33,444"

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 992 entries, 0 to 991
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   imdb_id      894 non-null    object
 1   title        894 non-null    object
 2   plot         866 non-null    object
 3   type         894 non-null    object
 4   rated        742 non-null    object
 5   year         894 non-null    object
 6   released_at  874 non-null    object
 7   added_at     992 non-null    object
 8   runtime      838 non-null    object
 9   genre        885 non-null    object
 10  director     689 non-null    object
 11  writer       743 non-null    object
 12  actors       870 non-null    object
 13  language     856 non-null    object
 14  country      869 non-null    object
 15  awards       556 non-null    object
 16  metascore    292 non-null    float64
 17  imdb_rating  879 non-null    float64
 18  imdb_votes   879 non-null    object
dtypes: float64(2), object(17)
memory usage: 147.4+ KB

In [36]:
df. describe()

        metascore  imdb_rating
count  292.000000   879.000000
mean    62.061644     6.656428
std     15.776455     1.020352
min     19.000000     1.500000
25%     51.000000     6.100000
50%     61.000000     6.700000
75%     73.000000     7.400000
max     99.000000     9.700000

In [37]:
df["type"].unique()

array(['movie', 'series', nan, 'episode'], dtype=object)

In [38]:
df["type"].unique()
df["year"].unique()[:30]
df["imdb_votes"].head(10)
df["genre"].head(10)

0                               Comedy, Drama, Romance
1                            Animation, Comedy, Family
2                     Adventure, Comedy, Crime, Family
3        Animation, Adventure, Comedy, Family, Musical
4                            Adventure, Comedy, Family
5                             Comedy, Fantasy, Romance
6            Adventure, Drama, Family, Fantasy, Sci-Fi
7                 Animation, Adventure, Comedy, Family
8                                                Music
9    Animation, Adventure, Comedy, Family, Musical,...
Name: genre, dtype: object

In [39]:
display(df["year"].unique()[:30])
display(df["imdb_votes"].head(10))

array(['1999', '2018–', '1996', '2002', '2000', '2011', '1954', '1998',
       '2020', '1995', '1946', '1977', '2018', '2019', '1992', '1994',
       '1951', '2010', '2005', '1949', '1962', '1989–', '2004', '2015–',
       '1981', '2017–2019', nan, '2017', '2003', '2001'], dtype=object)

0    283,945
1        124
2     97,785
3      7,434
4     33,444
5      4,933
6     27,761
7    257,065
8         35
9     43,655
Name: imdb_votes, dtype: object